import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import { parseDemo } from '../src/demo/parser';
import { ReplayIndex } from '../src/demo/replay';
import { createProxy,probe } from '../src/video/encode';
import { detectPreferences } from '../src/main/detect';
import { loadProject,saveProjectData,atomicJson } from '../src/main/projects';
import { newTactic,captureStep } from '../src/tactics/model';
const demo=process.argv[2];if(!demo)throw new Error('Usage: npm run test:demo -- "path/to/demo.dem"');
const directory=path.resolve('artifacts/integration');await fs.mkdir(directory,{recursive:true});
const match=await parseDemo(demo,directory,console.log);const frames=JSON.parse(await fs.readFile(path.join(directory,match.framesFile),'utf8'));
assert.equal(match.players.length,10);assert.equal(match.teams.length,2);assert.ok(match.rounds.length>0);assert.equal(match.tickRate,64);assert.ok(match.events.some(e=>e.type==='player_death'));assert.ok(match.utility.some(g=>g.kind==='smoke'));
const replay=new ReplayIndex(match,frames),tactic=newTactic(match.map,match.teams[0].id,demo);
for(let i=0;i<4;i++){const tick=match.rounds[0].freezeEndTick+i*64;tactic.steps[i]=captureStep(tactic.steps[i],tick,replay.frame(tick),replay.utility(tick));}
tactic.steps[2].annotations.push({id:'integration-arrow',kind:'arrow',color:'#edc76a',points:[[.3,.4],[.5,.6]]});
const preferences=await detectPreferences(process.cwd());
await saveProjectData({version:1,name:'Real demo integration',directory,demoPath:demo,matchDataPath:'match.json',selectedTeam:match.teams[0].id,pov:[],tactics:[tactic],preferences,mock:false});
const opened=await loadProject(path.join(directory,'project.json'));assert.deepEqual(opened.project.tactics[0],tactic);
await atomicJson(path.join(directory,'report.json'),{demo,map:match.map,players:match.players.length,teams:match.teams.map(t=>t.playerIds.length),rounds:match.rounds.length,frames:frames.length,events:match.events.length,utility:match.utility.length,tickRate:match.tickRate,fourStepsReopened:true,realPovVerified:false});console.log('PASS: real demo metadata, teams, samples, events and four-step persistence');
